### ISSUE TITLE
European 24h time format?

### ISSUE THREAD

**Issue by CoDEmanX** [mattkrick/lolliclock#1]
Your project looks really good! Just wondering if you have any plans to add support for 24h time format?

Here's a video from my Nexus 5, running Android 5.1:

https://youtu.be/vFnJ-HAPY8I

**Comment by mattkrick** [comment]
Thanks! I'm certainly not opposed to making it 24hr, but I haven't seen a
24hr version on android & I'm too terrible a designer to know how to make
it look good. I'd probably just put a second ring of numbers around the
first, but when I tried that the face looked crowded. If you can get me a
rendering of something that looks good I can implement it.

**Comment by CoDEmanX** [comment]
See the YouTube link in my initial post, that's how Google does it in the clock/timer app in material design!

Here's a screenshot:

![screenshot_2015-05-12-16-47-04](https://cloud.githubusercontent.com/assets/1309249/7590035/a567c91a-f8c6-11e4-9ea5-0f8461391bda.png)

The outer ring clearly uses a smaller font, but seems to be the same font weight. Due to the smaller digits, it appears less bold however.

**Comment by mattkrick** [comment]
Ah gotcha, thanks, work blocks YouTube so I was flying blind. For my
American eyes it still looks a little confusing at first glance, but I
suppose it's about as clean as it can get. It's crunch time right now on
another project but I should be able to add this option in the next couple
weeks

**Comment by fabyeah** [comment]
:+1: yes please, would be great!

Also, it would be awesome to have a meteor package :)

**Comment by kai23** [comment]
+1 :)

Too bad I can't use it right now (AM/PM is really odd in a European country like France) but you are the project I was looking for (a material timepicker, not a date picker).

I hope this project will advance :)

**Comment by boustanihani** [comment]
This Material-React-TimePicker already supports the european 24h time format, maybe you could borrow some code: http://material-ui.com/#/components/time-picker

**Comment by Casear** [comment]
@mattkrick  , I add 24 hours support on my fork [project](https://github.com/Casear/lolliclock).Should I send a pull request?

**Comment by boustanihani** [comment]
@Casear :+1:  for sending a pull request :bowtie:

**Comment by mattkrick** [comment]
Looks good from what I can tell, sure thing!

**Comment by mattkrick** [comment]
closed thanks to the great PR from @Casear
